micronaut:
  application:
    name: demo
  server:
    thread-selection: io
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    dialect: H2
jpa:
  default:
    entity-scan:
      enabled: true
owners:
  fred:
    name: Fred
    age: 35
    pets:
      - Dino
      - Baby Puss
  barney:
    name: Barney
    age: 30
    pets:
      - Hoppy
flyway:
  datasources:
    default:
      enabled: true
      baseline-on-migrate: true
      clean-schema: true
endpoints:
  all:
    enabled: true
    sensitive: false
  health:
    details-visible: anonymous